// Report-owned adapter. PostgreSQL selects versions, cohorts and denominators.
const c=(key,label,type='text')=>({key,label,type});
const columns={
 staff:[c('staffShiftKey','Staff / context key','identifier'),c('side','Comparison side','status'),c('userId','Staff ID','identifier'),c('staff','Staff (recorded/current label)'),c('staffTypeId','Recorded staff type ID','identifier'),c('staffType','Staff type'),
  c('rosterId','Underlying roster IDs','identifier'),c('periodId','Period ID','identifier'),c('shiftDate','Shift start date','date'),c('shift','Shift'),c('start','Actual shift start','datetime'),c('end','Actual shift end','datetime'),
  c('observationAt','Effective observation point','datetime'),c('evidenceThrough','Recording cutoff / plan baseline','datetime'),c('basis','Data basis','status'),c('rosterEvidence','Roster evidence','status'),c('rosterSnapshotRunId','Published roster snapshot run','identifier'),c('rosterCapturedAt','Roster record / snapshot time','datetime'),
  c('selectedUnit','Selected unit'),c('unitPatients','Known selected-unit patients','number'),c('fullKnownPatients','Known departmental assigned patients','number'),c('unknownLocations','Assigned patients with unknown location','number'),
  c('unitWorkload','Selected-unit workload points','number'),c('fullWorkload','Full known staff workload points','number'),c('adtIncluded','ADT points already included','number'),c('missingAssessments','Missing assessments / workload values','number'),c('missingRuleContexts','Missing frozen rule contexts','number'),c('unknownAllocations','Uncertain allocation evidence','number'),
  c('ruleVersions','Distinct frozen rule contexts','number'),c('ruleSignature','Rule snapshot signature','identifier'),c('highExtreme','Recorded HIGH + EXTREME patients','number'),c('extreme','Recorded EXTREME patients','number'),c('acuityDistribution','Acuity / rule distribution and points'),
  c('policyId','Capacity policy ID','identifier'),c('policy','Recorded capacity policy'),c('policyBasis','Limit evidence basis','status'),c('policyRunId','Published policy snapshot run','identifier'),c('policyCapturedAt','Policy reference / capture time','datetime'),
  c('maxWorkload','Workload limit (points)','number'),c('maxPatients','Patient limit','number'),c('maxHighExtreme','HIGH + EXTREME limit','number'),c('maxExtremeMetadata','Extreme-only limit (metadata)','number'),c('utilizationPercent','Workload utilization (%)','number'),
  c('capacityState','Evidence / capacity state','status'),c('knownLoadUnits','Units in known staff load'),c('encounterIds','Known assigned encounter IDs','identifier'),c('scopeNote','Scope / counting note')],
 allocations:[c('allocationKey','Side / encounter key','identifier'),c('side','Comparison side','status'),c('encounterId','Encounter record ID','identifier'),c('encounter','Encounter number','identifier'),c('patientId','Patient identifier','identifier'),c('patient','Patient (current authorized label)'),
  c('unitId','Effective unit ID','identifier'),c('unit','Effective unit'),c('unitContribution','Unit contribution','status'),c('allocationState','Published allocation evidence','status'),c('userId','Published staff ID','identifier'),c('staff','Published staff'),c('staffTypeId','Staff type ID','identifier'),c('staffType','Staff type'),
  c('assignmentId','Patient assignment ID','identifier'),c('assignmentVersion','Stored assignment version','identifier'),c('rosterId','Roster ID','identifier'),c('runId','Published run ID','identifier'),c('historyId','Publication history ID','identifier'),c('publishedAt','Publication recording time','datetime'),
  c('recordedReason','Recorded publication reason / note'),c('actorId','Publication actor ID','identifier'),c('actor','Publication actor (current label)'),c('shiftDate','Shift date','date'),c('shift','Shift'),c('start','Shift start','datetime'),c('end','Shift end','datetime'),c('observationAt','Observation point','datetime'),c('evidenceThrough','Evidence cutoff','datetime'),
  c('assessmentId','Assessment ID','identifier'),c('assessedAt','Assessment effective time','datetime'),c('assessmentRecordedAt','Assessment recording time','datetime'),c('workload','Recorded patient workload points','number'),c('adtIncluded','ADT already included','number'),c('acuity','Recorded acuity'),c('ruleSetId','Rule set ID','identifier'),c('ruleVersion','Frozen rule version','identifier'),c('ruleSignature','Rule snapshot signature','identifier'),c('source','Publication source','status'),c('publicationEvidence','Original publication evidence'),c('basis','Evidence basis')],
 continuity:[c('continuityKey','Boundary / encounter key','identifier'),c('encounterId','Encounter record ID','identifier'),c('encounter','Encounter number','identifier'),c('patientId','Patient identifier','identifier'),c('patient','Patient (current authorized label)'),c('status','Continuity classification','status'),
  c('outgoingStaff','Outgoing published staff'),c('incomingStaff','Incoming published staff'),c('outgoingUserId','Outgoing user ID','identifier'),c('incomingUserId','Incoming user ID','identifier'),c('outgoingAssignmentId','Outgoing assignment ID','identifier'),c('incomingAssignmentId','Incoming assignment ID','identifier'),
  c('outgoingState','Outgoing evidence','status'),c('incomingState','Incoming evidence','status'),c('outgoingHistoryId','Outgoing publication history ID','identifier'),c('incomingHistoryId','Incoming publication history ID','identifier'),c('outgoingPublishedAt','Outgoing publication time','datetime'),c('incomingPublishedAt','Incoming publication time','datetime'),
  c('incomingPublicationActorId','Incoming publication actor ID','identifier'),c('incomingPublicationActor','Incoming publication actor (current label)'),c('incomingPublicationReason','Incoming publication reason'),c('outgoingWorkload','Outgoing patient assessment points','number'),c('incomingWorkload','Incoming patient assessment points','number'),c('workloadDifference','Compatible patient points difference','number'),c('comparisonBasis','Metric comparison basis','status'),
  c('outgoingAssessmentId','Outgoing assessment ID','identifier'),c('incomingAssessmentId','Incoming assessment ID','identifier'),c('outgoingRuleSignature','Outgoing frozen rule signature','identifier'),c('incomingRuleSignature','Incoming frozen rule signature','identifier'),c('timeBasis','Publication / effective time meaning'),c('scopeBasis','Filter / denominator meaning')],
};
const limitations=[
 'This report compares two explicitly selected actual approved intervals, not a multi-shift pooled capacity or attendance record. Outgoing is observed immediately before its end or incoming start, whichever is earlier. Incoming is observed at its start. Future observations use current recorded plan/baseline.',
 'Latest published history/retained publication is selected per encounter and dated shift type/organization before staff filters. A later unassigned, ended or cancelled version does not reveal an older matching staff assignment. GENERATED, MANUAL_OVERRIDE draft history and optimizer before/after metrics are excluded.',
 'Staff rows are per person and actual context. Legacy duplicate roster IDs collapse to one denominator, with all IDs retained; conflicting captured policies are unavailable. Department-shared known load includes other units. Selected-unit contribution is separate and not labelled total staff load.',
 'Historical roster details use retained rows unchanged by cutoff or published staff snapshots. Removed/replaced contexts or uncaptured roster rows are unavailable, not reconstructed with current scheduling. Period membership uses the retained roster reference; snapshots do not preserve a complete schedule audit.',
 'Historical capacity is captured selected-unit publication evidence, not proof the policy never changed afterward. Current/future policy is read through the canonical staff pool only for a future plan. Missing policy is unknown; zero/nonpositive workload limits never create a percentage. Patient and HIGH+EXTREME checks follow existing limits; extreme-only limit is metadata.',
 'Assessment uses latest effective and recorded evidence at each cutoff. Workload already includes ADT: level workload + factor workload + ADT, never added twice. Points are not care hours. A missing assessment/workload, missing frozen rule context or mixed frozen rule contexts prevents a total/utilization; distributions retain separate contexts. No arbitrary safety score or expiry threshold.',
 'Known departmental patients are distinct encounters, not assignments or events. Incomplete allocation evidence prevents a complete workload percentage; known patient/acuity exceedances may still be documented. Missing location prevents a complete selected-unit contribution. No capacity sums across people, units or shifts.',
 'Continuity percentage = retained / (retained + changed) distinct selected-unit encounters with applicable published staff on both sides. Staff/type filters match either applicable side after version selection. Full-unit benchmark counts remain independent of display filters. Arrivals, departures and insufficient evidence are non-comparable.',
 'Incoming publication time/reason/actor records allocation, not the time responsibility was actually received. A different incoming nurse is a published comparison, not necessarily a recorded cross-shift reassignment event. No handover signature, owner or care delivered is inferred.',
 'Admission/discharge and dated location intervals are retained effective facts, not proof of what staff knew then; backdated corrections and silent location end edits are not fully audited. Expected discharge is ignored. Current patient labels are only read in the selected organization; moved/inaccessible labels stay unavailable.',
 'A boundary with no retained roster or patient allocation can return partial/empty evidence. Context-level missing roster/location/allocation counts describe the full scope, independent of staff filters. Reading never refreshes detectors, publishes, optimizes, evaluates historical eligibility or writes operational records.',
];
async function read(client,{actor,parameters}) {
 const {rows}=await client.query('SELECT shiftly_api.fn_handover_workload_continuity($1,$2::jsonb) value',[actor,parameters]);const d=rows[0].value;
 const section=(id,title,grain)=>({id,title,grain,evidenceBasis:'MIXED',availability:'AVAILABLE',columns:columns[id],rows:d[id],total:d[id].length,limitations:id==='staff'?[limitations[2],limitations[4],limitations[5]]:id==='continuity'?[limitations[7],limitations[8]]:[limitations[1],limitations[9]]});
 const metric=(label,key,definition)=>({label,value:d.totals[key],availability:d.totals[key]==null?'UNAVAILABLE':'AVAILABLE',definition});
 return {rowGrain:'Staff workload: one person / actual context. Continuity: one encounter across the selected pair.',workloadContext:d.context,contextSummaries:d.contexts,totals:d.totals,
  summaries:[metric('Selected staff shifts','staffShifts','One person per actual outgoing/incoming context; no shared capacity denominator.'),metric('Comparable encounters','comparableEncounters','Distinct selected-unit encounters with applicable published staff on both sides; selected staff/type scope.'),
   metric('Responsibility changed','changed','Different applicable published users on the two sides; not an attendance or signed handover event.'),metric('Responsibility retained','retained','Same applicable published user on both sides.'),
   metric('Recorded exceedances','documentedExceedances','Selected staff contexts with a known patient, workload or HIGH+EXTREME limit exceeded.'),metric('Continuity (%)','continuityPercent','Retained / (retained + changed) x 100. Excludes non-comparable encounters; unavailable when denominator is zero.')],
  metricDefinitions:[{id:'versions',label:'Publication version selection',definition:limitations[1]},{id:'workload',label:'Workload points and ADT',definition:limitations[5]},
   {id:'capacity',label:'Capacity and utilization',definition:'100 x compatible full known workload / positive recorded limit. Null with missing assessment, incompatible rules, missing policy or uncertain allocation. '+limitations[4]},
   {id:'continuity',label:'Continuity denominator',definition:limitations[7]},{id:'shared',label:'Shared staff',definition:limitations[2]}],sourceLimitations:limitations,
  sections:[section('staff','Staff Workload','person / actual context'),section('allocations','Published Patient Allocations','encounter / comparison side; includes explicit missing evidence'),section('continuity','Continuity','encounter / selected boundary pair')]};
}
async function lookup(client,{actor,field,parameters,search='',offset=0,value=null}) {
 const {rows}=await client.query('SELECT shiftly_api.fn_handover_workload_lookup($1,$2,$3::jsonb,$4,$5,$6) value',[actor,field,parameters,search,offset,value]);return rows[0].value;
}
module.exports={read,lookup};
